### ISSUE TITLE
gRPC has issues when used in conjunction with Electron to make a PC app

### ISSUE THREAD

**Issue by ottogutierrez** [googleapis/nodejs-dialogflow#211]
Hello,

I'm trying to make an electron app that makes call to DialogFlow API to make a chat bot.
Calls to DialogFlow work ok while my app is a nodejs application (server app). However, once I want to add the electron library to make it an pc or mac app, it gives me this error:

`App threw an error during load
Error: Failed to load gRPC binary module because it was not installed for the current system
Expected directory: electron-v3.0-darwin-x64-unknown
Found: [node-v64-darwin-x64-unknown]
This problem can often be fixed by running "npm rebuild" on the current system
Original error: Cannot find module '/Users/XXXXuserXXX/Documents/Developer/my-basic-chat/node_modules/grpc/src/node/extension_binary/electron-v3.0-darwin-x64-unknown/grpc_node.node'
    at Object.<anonymous> (/Users/XXXXuserXXX/Documents/Developer/my-basic-chat/node_modules/grpc/src/grpc_extension.js:53:17)
    at Object.<anonymous> (/Users/XXXXuserXXX/Documents/Developer/my-basic-chat/node_modules/grpc/src/grpc_extension.js:63:3)
    at Module._compile (internal/modules/cjs/loader.js:711:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:722:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
    at Function.Module._load (internal/modules/cjs/loader.js:551:3)
    at Module.require (internal/modules/cjs/loader.js:658:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/XXXXuserXXX/Documents/Developer/my-basic-chat/node_modules/grpc/src/client_interceptors.js:145:12) `

I have tried to run "npm rebuild" several times with no luck.
Is there a way to fix it?

**Comment by ottogutierrez** [comment]
I have also tried both Mac and Windows and I get the same issue

**Comment by ottogutierrez** [comment]
[Update]
I was able to fix this issue by rebuilding the gRPC for electron by using:
`npm install grpc --runtime=electron --target=[VERSION]`
Hopefully this helps to solve this problem

**Comment by JustinBeckwith** [comment]
Great to hear that you were able to get this rolling!

**Comment by lifeanddeath** [comment]
I use electron version 4.0.4 and still getting the same error.. Aforementioned comment of ottogutierez unfortunality didn't help.

**Comment by ottogutierrez** [comment]
hi @lifeanddeath , you are correct, i updated some packages today and it completely stopped working for me. I even tried to roll back to the previous packages and cannot fix it anymore... have you been able to fix it?
