### ISSUE TITLE
Module on AWS Lambda not working

### ISSUE THREAD

**Issue by MartinPindel** [googleapis/nodejs-dialogflow#226]
Hello,

I have the following problem.
I have developed a NodeJs-project on Windows 10, where I use the dialogflow module, which is working fine on my local system.

When I uploaded this project to AWS Lambda (based on Linux), I got the error message, that the directory **node-v57-linux-x64-glibc** is not found. So I downloaded this package manually and inserted it in the required directory.
But now I get the following error message, when the function **detectIntent** is called:
`TypeError: channel.createCall is not a function
at getCall (/var/task/node_modules/grpc/src/client_interceptors.js:651:22)
at /var/task/node_modules/grpc/src/client_interceptors.js:784:16
at /var/task/node_modules/grpc/src/client_interceptors.js:1381:14
at _buildChain (/var/task/node_modules/grpc/src/client_interceptors.js:1384:33)
at Object.getInterceptingCall (/var/task/node_modules/grpc/src/client_interceptors.js:1346:10)
at ServiceClient.Client.makeUnaryRequest (/var/task/node_modules/grpc/src/client.js:512:47)
at apply (/var/task/node_modules/lodash/lodash.js:478:17)
at ServiceClient.wrapper (/var/task/node_modules/lodash/lodash.js:5323:16)
at /var/task/node_modules/dialogflow/src/v2/sessions_client.js:148:39
at timeoutFunc (/var/task/node_modules/google-gax/build/src/api_callable.js:168:16)`

Can I fix this error somehow? Or is there another way to install the package for AWS Lambda?

Greetings
Martin

**Comment by roodrallec** [comment]
Rather than downloading the package, rebuild it:
`npm rebuild --target_platform=linux --target_arch=x64 --target_libc=glibc --update-binary`

**Comment by MartinPindel** [comment]
Thank you! This worked
