### ISSUE TITLE
API is not responding (Error: Retry total timeout exceeded before any response was received)

### ISSUE THREAD

**Issue by wtflove** [googleapis/nodejs-dialogflow#490]
#### Environment details

  - OS: win10
  - Node.js version: 10.14.1
  - npm version: 6.4.1
  - `dialogflow` version: 1.0.0
  - HTTP PROXY used

#### Problem describtion

The getAgent method is not responding any thing and eventually I will get a timeout error.
Although the API testing works good on DialogFlow api reference page, and googleapis/resource nodejs client works.

This works:
```javascript
const { Resource } = require('@google-cloud/resource');

// Creates a client
const resource = new Resource();

// Lists current projects
resource
    .getProjects()
    .then(results => {
        const projects = results[0];

        console.log('Projects:');
        projects.forEach(project => console.log(project.id));
    })
    .catch(err => {
        console.error('ERROR:', err);
    });
```

This doesn't:
```javascript
const dialogflow = require('dialogflow');

const formattedParent = client.projectPath('phonebook-ccpfxn');
console.log(formattedParent);
client.getAgent({ parent: formattedParent })
    .then(responses => {
        const response = responses[0];
        console.log(response);
        // doThingsWith(response)
    })
    .catch(err => {
        console.error(err);
    });
```
#### Error:
```
Error: Retry total timeout exceeded before any response was received
    at repeat (D:\GitHub\googleCloud\node_modules\google-gax\build\src\normalCalls\retries.js:80:31)
    at Timeout.setTimeout [as _onTimeout] (D:\GitHub\googleCloud\node_modules\google-gax\build\src\normalCalls\retries.js:113:25)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10) code: 4
```

Appreciate any help!

**Comment by callmehiphop** [comment]
👋 @wtflove so I don't think this client supports proxies out of the box unfortunately, I suspect that might be the root cause of what you're seeing. You can work around this by using the C core gRPC module instead.

```sh
$ npm i grpc
```

Then just import/pass it to the constructor

```js
const grpc = require('grpc');
const {v2} = require('dialogflow');

const client = new v2.AgentsClient({grpc});
```

Let me know if this helps at all

**Comment by wtflove** [comment]
@callmehiphop It works perfectlly! thank you!
