### ISSUE TITLE
Error: agent.json is missing , when using “importAgent” interface of dialogflow (node.js)

### ISSUE THREAD

**Issue by dSecret** [googleapis/nodejs-dialogflow#656]
I am using Dialogflow client on my Node.js server to import-agent using .zip file which I got from exporting agent through dialogflow console. This is the implementation -
```
const dialogflow = require("dialogflow");
const fs = require("fs");

const zipFile = "./exported_agent.zip";
const credentials = require("./credentials.json");

async function importAgent() { 
  try {
    // converting zip file to base64 format
    const base64ZipFile = await fs.readFileSync(zipFile).toString("base64");

    const client = new dialogflow.v2.AgentsClient({
      credentials,
      agentContent: base64ZipFile,
    });

    const formattedParent = client.projectPath("[PROJECT-ID]");

    [operation] = await client.importAgent({parent: formattedParent});
    [response] = await operation.promise();
    
    console.log(response)
  } catch(err) {
    console.log(err)
  }
}

importAgent()
```
But I am facing this error
```
Error: 3 INVALID_ARGUMENT: com.google.apps.framework.request.BadRequestException: Invalid agent zip. Missing required json file agent.json
    at Object.callErrorFromStatus (/home/ddark/Projects/IntentEntityApiTaskDialogflow/node_modules/@grpc/grpc-js/build/src/call.js:30:26)
    at Object.onReceiveStatus (/home/ddark/Projects/IntentEntityApiTaskDialogflow/node_modules/@grpc/grpc-js/build/src/client.js:175:52)
    at Object.onReceiveStatus (/home/ddark/Projects/IntentEntityApiTaskDialogflow/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:341:141)
    at Object.onReceiveStatus (/home/ddark/Projects/IntentEntityApiTaskDialogflow/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:304:181)
    at Http2CallStream.outputStatus (/home/ddark/Projects/IntentEntityApiTaskDialogflow/node_modules/@grpc/grpc-js/build/src/call-stream.js:116:74)
    at Http2CallStream.maybeOutputStatus (/home/ddark/Projects/IntentEntityApiTaskDialogflow/node_modules/@grpc/grpc-js/build/src/call-stream.js:155:22)
    at Http2CallStream.endCall (/home/ddark/Projects/IntentEntityApiTaskDialogflow/node_modules/@grpc/grpc-js/build/src/call-stream.js:141:18)
    at Http2CallStream.handleTrailers (/home/ddark/Projects/IntentEntityApiTaskDialogflow/node_modules/@grpc/grpc-js/build/src/call-stream.js:273:14)
    at ClientHttp2Stream.emit (events.js:314:20)
    at emit (internal/http2/core.js:291:8) {
  code: 3,
  details: 'com.google.apps.framework.request.BadRequestException: Invalid agent zip. Missing required json file agent.json',
  metadata: Metadata {
    internalRepr: Map(1) { 'grpc-server-stats-bin' => [Array] },
    options: {}
  }
}
```
On unzipping the .zip file, I can clearly see agent.json file. I have tried directly importing-agent (using same .zip file) through dialogflow console, it is working fine. But it is showing above error when I am trying to do it with the dialogflow client. I am following [this](https://cloud.google.com/nodejs/docs/reference/dialogflow/0.8.x/v2.AgentsClientl)

I appreciate any ideas on how can get this working again. Thanks!

**Comment by munkhuushmgl** [comment]
@dSecret I was able to reproduce your error

![image](https://user-images.githubusercontent.com/45373284/88729932-cc31e200-d0e9-11ea-9332-a35dff67067e.png)

Looking for a solution right now.

**Comment by hannanikulina** [comment]
The same issue for me.
I export an agent and immediately restore it to another project and receive the same error despite the fact that agent.json is in the zip.

**Comment by munkhuushmgl** [comment]
@hannanikulina  @dSecret Looks like you need to do is move the agentContent setting from your .AgentsClient() call to your .importAgent(), see the following:
```const dialogflow = require('@google-cloud/dialogflow').v2;
const fs = require("fs");

const zipFile = "./TEST_OUTPUT.zip";

async function importAgent() {
    try {
        // converting zip file to base64 format
        const base64ZipFile = await fs.readFileSync(zipFile).toString("base64");

        const client = new dialogflow.AgentsClient({
        });

        const formattedParent = client.projectPath("java-docs-samples-testing");

        [operation] = await client.importAgent({
            parent: formattedParent,
            agentContent: base64ZipFile

        });
        [response, oper] = await operation.promise();

        console.log(response)
        console.log(oper)
    } catch (err) {
        console.log(err)
    }
}

importAgent()
```

this should solve this problem.
