### ISSUE TITLE
connect ECONNREFUSED 142.250.74.202:443 - request to https://www.googleapis.com/oauth2/v4/token failed

### ISSUE THREAD

**Issue by mohan570** [googleapis/nodejs-dialogflow#712]
Hi Team,

In recently last two months only we are getting below error while using detectTextIntent method( const responses = await sessionClient.detectIntent(request); ) in detect.js file( https://github.com/googleapis/nodejs-dialogflow/blob/master/samples/detect.js ).

The Error,

code: 'ECONNREFUSED',
2020-09-16 07:17 +02:00:   details: 'Getting metadata from plugin failed with error: request to https://www.googleapis.com/oauth2/v4/token failed, reason: connect ECONNREFUSED 142.250.74.202:443',

Regards,
Mohan A

**Comment by bcoe** [comment]
@mohan570 what environment are you running the dialogflow library in? Do you connect through a proxy?

**Comment by mohan570** [comment]
> @mohan570 what environment are you running the dialogflow library in? Do you connect through a proxy?

Hi Bcoe, Yes am connecting through proxy. but its connecting sometimes and detect the intent periodically error coming like below,

"
 Error: Getting metadata from plugin failed with error: request to https://www.googleapis.com/oauth2/v4/token failed, reason: connect ECONNREFUSED 142.250.74.202:443
 at Http2CallStream.<anonymous> (Application\ChatBot_API\node_modules\dialogflow\node_modules\@grpc\grpc-js\build\src\client.js:102:45)
   at Http2CallStream.emit (events.js:322:22)
  at Http2CallStream.endCall (Application\ChatBot_API\node_modules\dialogflow\node_modules\@grpc\grpc-js\build\src\call-stream.js:74:18)
 at Application\ChatBot_API\node_modules\dialogflow\node_modules\@grpc\grpc-js\build\src\call-stream.js:355:18
 at runMicrotasks (<anonymous>)
 at processTicksAndRejections (internal/process/task_queues.js:97:5) {
 code: 'ECONNREFUSED',
 details: 'Getting metadata from plugin failed with error: request to https://www.googleapis.com/oauth2/v4/token failed, reason: connect ECONNREFUSED 142.250.74.202:443',
  metadata: Metadata { internalRepr: Map {} } }

Error: Deadline exceeded
   at Http2CallStream.<anonymous> (Application\ChatBot_API\node_modules\dialogflow\node_modules\@grpc\grpc-js\build\src\client.js:102:45)
  at Http2CallStream.emit (events.js:322:22)
  at Http2CallStream.endCall (Application\ChatBot_API\node_modules\dialogflow\node_modules\@grpc\grpc-js\build\src\call-stream.js:74:18)
  at Application\ChatBot_API\node_modules\dialogflow\node_modules\@grpc\grpc-js\build\src\call-stream.js:355:18 {
 code: 4,
 details: 'Deadline exceeded',
 metadata: Metadata { internalRepr: Map {} } }
"

NOTE : i checked the quote and pricing in dialogflow, there we have like 1200/per min.

**Comment by bcoe** [comment]
@mohan570 are you setting the `http_proxy` environment variable. Perhaps you're connecting directly to a Google IP, and having it rejected by your corporate proxy?

**Comment by mohan570** [comment]
> @mohan570 are you setting the `http_proxy` environment variable. Perhaps you're connecting directly to a Google IP, and having it rejected by your corporate proxy?

No we didnt http_proxy in environment variable

**Comment by ducvu91** [comment]
hello, it happened with me. i already testing with same case in many times. sometime happened, sometime not, not have specific case. 

**Error 1:**
Error: ECONNREFUSED undefined: Getting metadata from plugin failed with error: request to https://www.googleapis.com/oauth2/v4/token failed, reason: connect ECONNREFUSED xxxxxx:443
at Object.callErrorFromStatus (/root/node_modules/google-gax/node_modules/@grpc/grpc-js/build/src/call.js:30:26)

**Error 2:**
Error: 14 UNAVAILABLE: No connection established at Object.callErrorFromStatus (/root//node_modules/google-gax/node_modules/@grpc/grpc-js/build/src/call.js:30:26)

**Error in another same project:**
 Auth error:FetchError: request to https://www.googleapis.com/oauth2/v4/token failed, reason: connect ECONNREFUSED xxxxxxx:443
Error: 14 UNAVAILABLE: Getting metadata from plugin failed with error: request to https://www.googleapis.com/oauth2/v4/token failed, reason: connect ECONNREFUSED xxxxxxx:443
 at Object.exports.createStatusError (/root/node_modules/grpc/src/common.js:91:15)

**Comment by glen-lee** [comment]
I would like to report similar issues.

But outside of ECONNREFUSED and 14 UNAVAILABLE, I've also been getting 
Error: 4 DEADLINE_EXCEEDED: Deadline exceeded
    at Object.callErrorFromStatus (/app/node_modules/@grpc/grpc-js/build/src/call.js:31:26)
    at Object.onReceiveStatus (/app/node_modules/@grpc/grpc-js/build/src/client.js:176:52)
    at Object.onReceiveStatus (/app/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:336:141)
    at Object.onReceiveStatus (/app/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:299:181)
    at /app/node_modules/@grpc/grpc-js/build/src/call-stream.js:130:78
    at processTicksAndRejections (internal/process/task_queues.js:79:11)

**Comment by bcoe** [comment]
@glen-lee @ducvu91 how are you interacting with dialogflow? 

* are you using a GoogleCloud product (_such as Cloud Run_) or are you connecting from your local machine or a corporate network?
* are you connecting through a corporate proxy?

**Comment by glen-lee** [comment]
> @glen-lee @ducvu91 how are you interacting with dialogflow?
> 
> * are you using a GoogleCloud product (_such as Cloud Run_) or are you connecting from your local machine or a corporate network?
> * are you connecting through a corporate proxy?

Hi, bcoe
1. I am not using Cloud Run. I am connecting from a production server through corporate network
2. I have asked the network admin and we don't use proxies. I have also checked the `http_proxy `& `https_proxy` env and none are set

In my case this problem occurs randomly. Sometimes I could send hundreds of requests with no problem at all but other times even 1 request will result in `ETIMEDOUT `or `14 UNAVAILABLE` but it's not permanent, after several more attempts the results will be returned. No process restart or anything.

The errors appear during `detectIntent() `call.

**Comment by bcoe** [comment]
@glen-lee could you try running your application with the following environment variables set:

`GRPC_TRACE=all GRPC_VERBOSITY=DEBUG `

And share the log output when an error occurs?

**Comment by glen-lee** [comment]
> @glen-lee could you try running your application with the following environment variables set:
> 
> `GRPC_TRACE=all GRPC_VERBOSITY=DEBUG `
> 
> And share the log output when an error occurs?

Hello, here are the logs on my server. I had both of those env set.

ETIMEDOUT:
```
2021-02-16T07:44:10.224Z | call_stream | [0] cancelWithStatus code: ETIMEDOUT details: "Getting metadata from plugin failed with error: request to https://www.googleapis.com/oauth2/v4/token failed, reason: connect ETIMEDOUT 172.217.194.95:443"
2021-02-16T07:44:10.225Z | call_stream | [0] ended with status: code=ETIMEDOUT details="Getting metadata from plugin failed with error: request to https://www.googleapis.com/oauth2/v4/token failed, reason: connect ETIMEDOUT 172.217.194.95:443"

Tue Feb 16 2021 07:44:10 GMT+0000 (Coordinated Universal Time) ERROR_LOG : Error: ETIMEDOUT undefined: Getting metadata from plugin failed with error: request to https://www.googleapis.com/oauth2/v4/token failed, reason: connect ETIMEDOUT 172.217.194.95:443
    at Object.callErrorFromStatus (/app/node_modules/@grpc/grpc-js/build/src/call.js:30:26)
    at Object.onReceiveStatus (/app/node_modules/@grpc/grpc-js/build/src/client.js:175:52)
    at Object.onReceiveStatus (/app/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:341:141)
    at Object.onReceiveStatus (/app/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:304:181)
    at Http2CallStream.outputStatus (/app/node_modules/@grpc/grpc-js/build/src/call-stream.js:116:74)
    at Http2CallStream.maybeOutputStatus (/app/node_modules/@grpc/grpc-js/build/src/call-stream.js:155:22)
    at Http2CallStream.endCall (/app/node_modules/@grpc/grpc-js/build/src/call-stream.js:141:18)
    at Http2CallStream.cancelWithStatus (/app/node_modules/@grpc/grpc-js/build/src/call-stream.js:457:14)
    at /app/node_modules/@grpc/grpc-js/build/src/channel.js:225:36
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

14 UNAVAILABLE:
```
2021-02-16T14:44:52.718Z | subchannel | 172.217.194.95:443 connection closed with error connect ETIMEDOUT 172.217.194.95:443
2021-02-16T14:44:52.720Z | subchannel | 172.217.194.95:443 CONNECTING -> TRANSIENT_FAILURE
2021-02-16T14:44:52.720Z | pick_first | CONNECTING -> TRANSIENT_FAILURE
2021-02-16T14:44:52.720Z | resolving_load_balancer | dns:dialogflow.googleapis.com:443 CONNECTING -> TRANSIENT_FAILURE
2021-02-16T14:44:52.720Z | channel | Pick result: TRANSIENT_FAILURE subchannel: undefined status: 14 No connection established
2021-02-16T14:44:52.720Z | call_stream | [2] cancelWithStatus code: 14 details: "No connection established"
2021-02-16T14:44:52.720Z | call_stream | [2] ended with status: code=14 details="No connection established"
2021-02-16T14:44:52.720Z | connectivity_state | dns:dialogflow.googleapis.com:443 CONNECTING -> TRANSIENT_FAILURE
2021-02-16T14:44:52.721Z | subchannel | 172.217.194.95:443 TRANSIENT_FAILURE -> IDLE
2021-02-16T14:44:52.721Z | subchannel | 2404:6800:4003:c04::5f:443 refcount 2 -> 1
2021-02-16T14:44:52.721Z | subchannel | 172.217.194.95:443 refcount 2 -> 1
2021-02-16T14:44:52.721Z | pick_first | TRANSIENT_FAILURE -> IDLE
2021-02-16T14:44:52.721Z | resolving_load_balancer | dns:dialogflow.googleapis.com:443 TRANSIENT_FAILURE -> IDLE
2021-02-16T14:44:52.721Z | connectivity_state | dns:dialogflow.googleapis.com:443 TRANSIENT_FAILURE -> IDLE

Tue Feb 16 2021 14:44:52 GMT+0000 (Coordinated Universal Time) ERROR_LOG : Error: 14 UNAVAILABLE: No connection established
    at Object.callErrorFromStatus (/app/node_modules/@grpc/grpc-js/build/src/call.js:30:26)
    at Object.onReceiveStatus (/app/node_modules/@grpc/grpc-js/build/src/client.js:175:52)
    at Object.onReceiveStatus (/app/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:341:141)
    at Object.onReceiveStatus (/app/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:304:181)
    at Http2CallStream.outputStatus (/app/node_modules/@grpc/grpc-js/build/src/call-stream.js:116:74)
    at Http2CallStream.maybeOutputStatus (/app/node_modules/@grpc/grpc-js/build/src/call-stream.js:155:22)
    at Http2CallStream.endCall (/app/node_modules/@grpc/grpc-js/build/src/call-stream.js:141:18)
    at Http2CallStream.cancelWithStatus (/app/node_modules/@grpc/grpc-js/build/src/call-stream.js:457:14)
    at ChannelImplementation.tryPick (/app/node_modules/@grpc/grpc-js/build/src/channel.js:237:32)
    at Object.updateState (/app/node_modules/@grpc/grpc-js/build/src/channel.js:106:26)
    at ResolvingLoadBalancer.updateState (/app/node_modules/@grpc/grpc-js/build/src/resolving-load-balancer.js:180:35)
    at Object.updateState (/app/node_modules/@grpc/grpc-js/build/src/resolving-load-balancer.js:88:22)
    at ChildLoadBalancerHandler.ChildPolicyHelper.updateState (/app/node_modules/@grpc/grpc-js/build/src/load-balancer-child-handler.js:48:50)
    at PickFirstLoadBalancer.updateState (/app/node_modules/@grpc/grpc-js/build/src/load-balancer-pick-first.js:243:35)
    at PickFirstLoadBalancer.subchannelStateListener (/app/node_modules/@grpc/grpc-js/build/src/load-balancer-pick-first.js:136:38)
    at Subchannel.transitionToState (/app/node_modules/@grpc/grpc-js/build/src/subchannel.js:381:13)

```

**Comment by bcoe** [comment]
@mohan570 was your problem solved by setting the `http_proxy` variable?

@glen-lee could you open a new issue describing your specific issue?

**Comment by sgreenberg** [comment]
Thank you for filing this issue. We asked some clarifying questions a week or more ago and never heard back from you. We are unable to proceed with this issue until then, so we are closing it. Please feel free to re-open this issue with more information.
