### ISSUE TITLE
PERMISSION_DENIED: IAM permission 'dialogflow.sessions.detectIntent' on 'projects/lead-gen-wjd9/agent' denied.

### ISSUE THREAD

**Issue by pranjalvatsa** [googleapis/nodejs-dialogflow#819]
I am getting a permission denied error when trying to call DialogFlow API from my Nodejs webhook from Twlio. I have given DialogFlow API Admin role to the service account created.

**Comment by b-loved-dreamer** [comment]
Hi @pranjalvatsa. Can you please share more details? In the meantime, make sure you're following the setup steps in the doc [page](https://cloud.google.com/dialogflow/cx/docs/quick/setup).

**Comment by patlim8** [comment]
I get this problem too. i try using this code from Google cloud
[https://cloud.google.com/dialogflow/es/docs/quick/api](url)

botan-2 is my project id in Google cloud platform

`/**
 * TODO(developer): UPDATE these variables before running the sample.
 */
// projectId: ID of the GCP project where Dialogflow agent is deployed
const projectId = 'botan-2';
// sessionId: String representing a random number or hashed user identifier
const sessionId = '123456';
// queries: A set of sequential queries to be send to Dialogflow agent for Intent Detection
const queries = [
  'Hi',
  'Hello', // Tell the bot when the meeting is taking place
  'B'  // Rooms are defined on the Dialogflow agent, default options are A, B, or C
]
// languageCode: Indicates the language Dialogflow agent should use to detect intents
const languageCode = 'en';

// Imports the Dialogflow library
const dialogflow = require('@google-cloud/dialogflow');

// Instantiates a session client
const sessionClient = new dialogflow.SessionsClient();

async function detectIntent(
  projectId,
  sessionId,
  query,
  contexts,
  languageCode
) {
  // The path to identify the agent that owns the created intent.
  const sessionPath = sessionClient.projectAgentSessionPath(
    projectId,
    sessionId
  );

  // The text query request.
  const request = {
    session: sessionPath,
    queryInput: {
      text: {
        text: query,
        languageCode: languageCode,
      },
    },
  };

  if (contexts && contexts.length > 0) {
    request.queryParams = {
      contexts: contexts,
    };
  }

  const responses = await sessionClient.detectIntent(request);
  return responses[0];
}

async function executeQueries(projectId, sessionId, queries, languageCode) {
  // Keeping the context across queries let's us simulate an ongoing conversation with the bot
  let context;
  let intentResponse;
  for (const query of queries) {
    try {
      console.log(`Sending Query: ${query}`);
      intentResponse = await detectIntent(
        projectId,
        sessionId,
        query,
        context,
        languageCode
      );
      console.log('Detected intent');
      console.log(
        `Fulfillment Text: ${intentResponse.queryResult.fulfillmentText}`
      );
      // Use the context from this response for next queries
      context = intentResponse.queryResult.outputContexts;
    } catch (error) {
      console.log(error);
    }
  }
}
executeQueries(projectId, sessionId, queries, languageCode);`


here is error I got when executing my code

> Sending Query: Hi
Error: 7 PERMISSION_DENIED: IAM permission 'dialogflow.sessions.detectIntent' on 'projects/botan-2/agent' denied.
    at Object.callErrorFromStatus (C:\Users\tanap\codes\myPractice\nodejs-dialogflow\samples\node_modules\@grpc\grpc-js\build\src\call.js:31:26)
    at Object.onReceiveStatus (C:\Users\tanap\codes\myPractice\nodejs-dialogflow\samples\node_modules\@grpc\grpc-js\build\src\client.js:179:52)
    at Object.onReceiveStatus (C:\Users\tanap\codes\myPractice\nodejs-dialogflow\samples\node_modules\@grpc\grpc-js\build\src\client-interceptors.js:336:141)
    at Object.onReceiveStatus (C:\Users\tanap\codes\myPractice\nodejs-dialogflow\samples\node_modules\@grpc\grpc-js\build\src\client-interceptors.js:299:181)
    at C:\Users\tanap\codes\myPractice\nodejs-dialogflow\samples\node_modules\@grpc\grpc-js\build\src\call-stream.js:145:78
    at processTicksAndRejections (internal/process/task_queues.js:75:11) {
  code: 7,
  details: "IAM permission 'dialogflow.sessions.detectIntent' on 'projects/botan-2/agent' denied.",
  metadata: Metadata {
    internalRepr: Map(1) { 'grpc-server-stats-bin' => [Array] },
    options: {}
  },
  note: 'Exception occurred in retry method that was not classified as transient'
}
Sending Query: Hello
Error: 7 PERMISSION_DENIED: IAM permission 'dialogflow.sessions.detectIntent' on 'projects/botan-2/agent' denied.
    at Object.callErrorFromStatus (C:\Users\tanap\codes\myPractice\nodejs-dialogflow\samples\node_modules\@grpc\grpc-js\build\src\call.js:31:26)
    at Object.onReceiveStatus (C:\Users\tanap\codes\myPractice\nodejs-dialogflow\samples\node_modules\@grpc\grpc-js\build\src\client.js:179:52)
    at Object.onReceiveStatus (C:\Users\tanap\codes\myPractice\nodejs-dialogflow\samples\node_modules\@grpc\grpc-js\build\src\client-interceptors.js:336:141)
    at Object.onReceiveStatus (C:\Users\tanap\codes\myPractice\nodejs-dialogflow\samples\node_modules\@grpc\grpc-js\build\src\client-interceptors.js:299:181)
    at C:\Users\tanap\codes\myPractice\nodejs-dialogflow\samples\node_modules\@grpc\grpc-js\build\src\call-stream.js:145:78
    at processTicksAndRejections (internal/process/task_queues.js:75:11) {
  code: 7,
  details: "IAM permission 'dialogflow.sessions.detectIntent' on 'projects/botan-2/agent' denied.",
  metadata: Metadata {
    internalRepr: Map(1) { 'grpc-server-stats-bin' => [Array] },
    options: {}
  },
  note: 'Exception occurred in retry method that was not classified as transient'
}
Sending Query: B
Error: 7 PERMISSION_DENIED: IAM permission 'dialogflow.sessions.detectIntent' on 'projects/botan-2/agent' denied.
    at Object.callErrorFromStatus (C:\Users\tanap\codes\myPractice\nodejs-dialogflow\samples\node_modules\@grpc\grpc-js\build\src\call.js:31:26)
    at Object.onReceiveStatus (C:\Users\tanap\codes\myPractice\nodejs-dialogflow\samples\node_modules\@grpc\grpc-js\build\src\client.js:179:52)
    at Object.onReceiveStatus (C:\Users\tanap\codes\myPractice\nodejs-dialogflow\samples\node_modules\@grpc\grpc-js\build\src\client-interceptors.js:336:141)
    at Object.onReceiveStatus (C:\Users\tanap\codes\myPractice\nodejs-dialogflow\samples\node_modules\@grpc\grpc-js\build\src\client-interceptors.js:299:181)
    at C:\Users\tanap\codes\myPractice\nodejs-dialogflow\samples\node_modules\@grpc\grpc-js\build\src\call-stream.js:145:78
    at processTicksAndRejections (internal/process/task_queues.js:75:11) {
  code: 7,
  details: "IAM permission 'dialogflow.sessions.detectIntent' on 'projects/botan-2/agent' denied.",
  metadata: Metadata {
    internalRepr: Map(1) { 'grpc-server-stats-bin' => [Array] },
    options: {}
  },
  note: 'Exception occurred in retry method that was not classified as transient'
}

**Comment by patlim8** [comment]
mine is solved now, I solve it by creating new service account and authenticate with new key.

**Comment by pranjalvatsa** [comment]
Yes, this issue got resolved for me as well. Creating a new account did the trick.
